// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/config/logging_config.proto

#ifndef PROTOBUF_INCLUDED_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto
#define PROTOBUF_INCLUDED_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow_serving/config/log_collector_config.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto 

namespace protobuf_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto
namespace tensorflow {
namespace serving {
class LoggingConfig;
class LoggingConfigDefaultTypeInternal;
extern LoggingConfigDefaultTypeInternal _LoggingConfig_default_instance_;
class SamplingConfig;
class SamplingConfigDefaultTypeInternal;
extern SamplingConfigDefaultTypeInternal _SamplingConfig_default_instance_;
}  // namespace serving
}  // namespace tensorflow
namespace google {
namespace protobuf {
template<> ::tensorflow::serving::LoggingConfig* Arena::CreateMaybeMessage<::tensorflow::serving::LoggingConfig>(Arena*);
template<> ::tensorflow::serving::SamplingConfig* Arena::CreateMaybeMessage<::tensorflow::serving::SamplingConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tensorflow {
namespace serving {

// ===================================================================

class SamplingConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.SamplingConfig) */ {
 public:
  SamplingConfig();
  virtual ~SamplingConfig();

  SamplingConfig(const SamplingConfig& from);

  inline SamplingConfig& operator=(const SamplingConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SamplingConfig(SamplingConfig&& from) noexcept
    : SamplingConfig() {
    *this = ::std::move(from);
  }

  inline SamplingConfig& operator=(SamplingConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const SamplingConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SamplingConfig* internal_default_instance() {
    return reinterpret_cast<const SamplingConfig*>(
               &_SamplingConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(SamplingConfig* other);
  void Swap(SamplingConfig* other);
  friend void swap(SamplingConfig& a, SamplingConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SamplingConfig* New() const final {
    return CreateMaybeMessage<SamplingConfig>(NULL);
  }

  SamplingConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SamplingConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SamplingConfig& from);
  void MergeFrom(const SamplingConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SamplingConfig* other);
  protected:
  explicit SamplingConfig(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double sampling_rate = 1;
  void clear_sampling_rate();
  static const int kSamplingRateFieldNumber = 1;
  double sampling_rate() const;
  void set_sampling_rate(double value);

  // @@protoc_insertion_point(class_scope:tensorflow.serving.SamplingConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double sampling_rate_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LoggingConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.LoggingConfig) */ {
 public:
  LoggingConfig();
  virtual ~LoggingConfig();

  LoggingConfig(const LoggingConfig& from);

  inline LoggingConfig& operator=(const LoggingConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoggingConfig(LoggingConfig&& from) noexcept
    : LoggingConfig() {
    *this = ::std::move(from);
  }

  inline LoggingConfig& operator=(LoggingConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoggingConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoggingConfig* internal_default_instance() {
    return reinterpret_cast<const LoggingConfig*>(
               &_LoggingConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void UnsafeArenaSwap(LoggingConfig* other);
  void Swap(LoggingConfig* other);
  friend void swap(LoggingConfig& a, LoggingConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoggingConfig* New() const final {
    return CreateMaybeMessage<LoggingConfig>(NULL);
  }

  LoggingConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LoggingConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LoggingConfig& from);
  void MergeFrom(const LoggingConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoggingConfig* other);
  protected:
  explicit LoggingConfig(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .tensorflow.serving.LogCollectorConfig log_collector_config = 1;
  bool has_log_collector_config() const;
  void clear_log_collector_config();
  static const int kLogCollectorConfigFieldNumber = 1;
  private:
  const ::tensorflow::serving::LogCollectorConfig& _internal_log_collector_config() const;
  public:
  const ::tensorflow::serving::LogCollectorConfig& log_collector_config() const;
  ::tensorflow::serving::LogCollectorConfig* release_log_collector_config();
  ::tensorflow::serving::LogCollectorConfig* mutable_log_collector_config();
  void set_allocated_log_collector_config(::tensorflow::serving::LogCollectorConfig* log_collector_config);
  void unsafe_arena_set_allocated_log_collector_config(
      ::tensorflow::serving::LogCollectorConfig* log_collector_config);
  ::tensorflow::serving::LogCollectorConfig* unsafe_arena_release_log_collector_config();

  // .tensorflow.serving.SamplingConfig sampling_config = 2;
  bool has_sampling_config() const;
  void clear_sampling_config();
  static const int kSamplingConfigFieldNumber = 2;
  private:
  const ::tensorflow::serving::SamplingConfig& _internal_sampling_config() const;
  public:
  const ::tensorflow::serving::SamplingConfig& sampling_config() const;
  ::tensorflow::serving::SamplingConfig* release_sampling_config();
  ::tensorflow::serving::SamplingConfig* mutable_sampling_config();
  void set_allocated_sampling_config(::tensorflow::serving::SamplingConfig* sampling_config);
  void unsafe_arena_set_allocated_sampling_config(
      ::tensorflow::serving::SamplingConfig* sampling_config);
  ::tensorflow::serving::SamplingConfig* unsafe_arena_release_sampling_config();

  // @@protoc_insertion_point(class_scope:tensorflow.serving.LoggingConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::tensorflow::serving::LogCollectorConfig* log_collector_config_;
  ::tensorflow::serving::SamplingConfig* sampling_config_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SamplingConfig

// double sampling_rate = 1;
inline void SamplingConfig::clear_sampling_rate() {
  sampling_rate_ = 0;
}
inline double SamplingConfig::sampling_rate() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SamplingConfig.sampling_rate)
  return sampling_rate_;
}
inline void SamplingConfig::set_sampling_rate(double value) {
  
  sampling_rate_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.serving.SamplingConfig.sampling_rate)
}

// -------------------------------------------------------------------

// LoggingConfig

// .tensorflow.serving.LogCollectorConfig log_collector_config = 1;
inline bool LoggingConfig::has_log_collector_config() const {
  return this != internal_default_instance() && log_collector_config_ != NULL;
}
inline const ::tensorflow::serving::LogCollectorConfig& LoggingConfig::_internal_log_collector_config() const {
  return *log_collector_config_;
}
inline const ::tensorflow::serving::LogCollectorConfig& LoggingConfig::log_collector_config() const {
  const ::tensorflow::serving::LogCollectorConfig* p = log_collector_config_;
  // @@protoc_insertion_point(field_get:tensorflow.serving.LoggingConfig.log_collector_config)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::serving::LogCollectorConfig*>(
      &::tensorflow::serving::_LogCollectorConfig_default_instance_);
}
inline ::tensorflow::serving::LogCollectorConfig* LoggingConfig::release_log_collector_config() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.LoggingConfig.log_collector_config)
  
  ::tensorflow::serving::LogCollectorConfig* temp = log_collector_config_;
  if (GetArenaNoVirtual() != NULL) {
    temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
  }
  log_collector_config_ = NULL;
  return temp;
}
inline ::tensorflow::serving::LogCollectorConfig* LoggingConfig::unsafe_arena_release_log_collector_config() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.LoggingConfig.log_collector_config)
  
  ::tensorflow::serving::LogCollectorConfig* temp = log_collector_config_;
  log_collector_config_ = NULL;
  return temp;
}
inline ::tensorflow::serving::LogCollectorConfig* LoggingConfig::mutable_log_collector_config() {
  
  if (log_collector_config_ == NULL) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::LogCollectorConfig>(GetArenaNoVirtual());
    log_collector_config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.LoggingConfig.log_collector_config)
  return log_collector_config_;
}
inline void LoggingConfig::set_allocated_log_collector_config(::tensorflow::serving::LogCollectorConfig* log_collector_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(log_collector_config_);
  }
  if (log_collector_config) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(log_collector_config)->GetArena();
    if (message_arena != submessage_arena) {
      log_collector_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, log_collector_config, submessage_arena);
    }
    
  } else {
    
  }
  log_collector_config_ = log_collector_config;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.LoggingConfig.log_collector_config)
}

// .tensorflow.serving.SamplingConfig sampling_config = 2;
inline bool LoggingConfig::has_sampling_config() const {
  return this != internal_default_instance() && sampling_config_ != NULL;
}
inline void LoggingConfig::clear_sampling_config() {
  if (GetArenaNoVirtual() == NULL && sampling_config_ != NULL) {
    delete sampling_config_;
  }
  sampling_config_ = NULL;
}
inline const ::tensorflow::serving::SamplingConfig& LoggingConfig::_internal_sampling_config() const {
  return *sampling_config_;
}
inline const ::tensorflow::serving::SamplingConfig& LoggingConfig::sampling_config() const {
  const ::tensorflow::serving::SamplingConfig* p = sampling_config_;
  // @@protoc_insertion_point(field_get:tensorflow.serving.LoggingConfig.sampling_config)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::serving::SamplingConfig*>(
      &::tensorflow::serving::_SamplingConfig_default_instance_);
}
inline ::tensorflow::serving::SamplingConfig* LoggingConfig::release_sampling_config() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.LoggingConfig.sampling_config)
  
  ::tensorflow::serving::SamplingConfig* temp = sampling_config_;
  if (GetArenaNoVirtual() != NULL) {
    temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
  }
  sampling_config_ = NULL;
  return temp;
}
inline ::tensorflow::serving::SamplingConfig* LoggingConfig::unsafe_arena_release_sampling_config() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.LoggingConfig.sampling_config)
  
  ::tensorflow::serving::SamplingConfig* temp = sampling_config_;
  sampling_config_ = NULL;
  return temp;
}
inline ::tensorflow::serving::SamplingConfig* LoggingConfig::mutable_sampling_config() {
  
  if (sampling_config_ == NULL) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::SamplingConfig>(GetArenaNoVirtual());
    sampling_config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.LoggingConfig.sampling_config)
  return sampling_config_;
}
inline void LoggingConfig::set_allocated_sampling_config(::tensorflow::serving::SamplingConfig* sampling_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete sampling_config_;
  }
  if (sampling_config) {
    ::google::protobuf::Arena* submessage_arena =
      ::google::protobuf::Arena::GetArena(sampling_config);
    if (message_arena != submessage_arena) {
      sampling_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sampling_config, submessage_arena);
    }
    
  } else {
    
  }
  sampling_config_ = sampling_config;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.LoggingConfig.sampling_config)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace serving
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_tensorflow_5fserving_2fconfig_2flogging_5fconfig_2eproto
