# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diplomacy_tensorflow/compiler/xla/service/gpu/backend_configs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diplomacy_tensorflow/compiler/xla/service/gpu/backend_configs.proto',
  package='xla.gpu',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nCdiplomacy_tensorflow/compiler/xla/service/gpu/backend_configs.proto\x12\x07xla.gpu\"\x95\x01\n\x16\x43udnnConvBackendConfig\x12\x11\n\talgorithm\x18\x01 \x01(\x03\x12\x1a\n\x12tensor_ops_enabled\x18\x02 \x01(\x08\x12\x19\n\x11\x63onv_result_scale\x18\x04 \x01(\x01\x12\x17\n\x0f\x61\x63tivation_mode\x18\x03 \x01(\x03\x12\x18\n\x10side_input_scale\x18\x05 \x01(\x01\x62\x06proto3')
)




_CUDNNCONVBACKENDCONFIG = _descriptor.Descriptor(
  name='CudnnConvBackendConfig',
  full_name='xla.gpu.CudnnConvBackendConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='xla.gpu.CudnnConvBackendConfig.algorithm', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensor_ops_enabled', full_name='xla.gpu.CudnnConvBackendConfig.tensor_ops_enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conv_result_scale', full_name='xla.gpu.CudnnConvBackendConfig.conv_result_scale', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_mode', full_name='xla.gpu.CudnnConvBackendConfig.activation_mode', index=3,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='side_input_scale', full_name='xla.gpu.CudnnConvBackendConfig.side_input_scale', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['CudnnConvBackendConfig'] = _CUDNNCONVBACKENDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CudnnConvBackendConfig = _reflection.GeneratedProtocolMessageType('CudnnConvBackendConfig', (_message.Message,), dict(
  DESCRIPTOR = _CUDNNCONVBACKENDCONFIG,
  __module__ = 'diplomacy_tensorflow.compiler.xla.service.gpu.backend_configs_pb2'
  # @@protoc_insertion_point(class_scope:xla.gpu.CudnnConvBackendConfig)
  ))
_sym_db.RegisterMessage(CudnnConvBackendConfig)


# @@protoc_insertion_point(module_scope)
