Bootstrap: localimage
From: /data/ubuntu-cuda10-20190226.sif

%runscript
cd /data/diplomacy
mkdir -p /work_dir/redis

# Moving default redis conf
if [ ! -f /work_dir/redis/redis.conf ]; then
    cp /data/redis.conf /work_dir/redis/redis.conf
fi

# Executing
exec "$@"

%environment
export WORKING_DIR=/work_dir/diplomacy
export HOME="${HOME:-/work_dir}"
export CUDA_HOME=/usr/local/cuda
export CUDA_ROOT=$CUDA_HOME
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$CUDA_HOME/extras/CUPTI/lib64:/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib64
export PATH=/data/env3.7/bin:$PATH
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
export PYTHONIOENCODING=utf-8
export LANG=en_CA.UTF-8
export PYTHONUNBUFFERED=1

%labels
AUTHOR pcpaquette@gmail.com

%setup
cp /home/jenkins/.container/build_args $SINGULARITY_ROOTFS/root/build_args
cp /home/jenkins/.container/redis.conf ${SINGULARITY_ROOTFS}/redis.conf

%post
# Creating directories
mkdir -p /scratch
mkdir -p /cvmfs
. /root/build_args

# Cloning repo
mkdir -p /data
mkdir -p /work_dir/diplomacy
cd /data
mv /redis.conf /data/redis.conf
git clone "https://$GITHUB_TOKEN:x-oauth-basic@github.com/$REPO.git" diplomacy

# Installing Anaconda - Python3.7 with dependencies
wget -nv https://storage.googleapis.com/ppaquette-diplomacy/files/Miniconda3-py37.sh -O miniconda.sh
bash ./miniconda.sh -b -p /data/env3.7
export PATH="/data/env3.7/bin:$PATH"
cd diplomacy
git checkout $COMMIT_ID
./diplomacy_research/scripts/build_proto.sh
./.jenkins/expand_vars.sh
pip install -r requirements.txt
pip install -r requirements_dev.txt
git checkout -- requirements.txt requirements_dev.txt
python -m compileall .

# Installing TF Serving dummy
cd /data
wget -nv https://storage.googleapis.com/ppaquette-diplomacy/files/serving.zip -O serving.zip
unzip serving.zip
rm -f serving.zip

# Removing Tensorflow and installing custom TensorFlow
if [ "${BRANCH:-master}" != "build_cpu" ]; then
    pip uninstall -y tensorflow
    cd /data
    pip install /data/tensorflow*.whl
fi
chmod -R 777 /data
chmod -R 777 /work_dir

# Deleting pip cache
rm -Rf /tmp/pip_build_root
